-- WSU Full Course Catalog Seed Data
-- Source: https://catalog.westfield.ma.edu/content.php?catoid=37&navoid=1745
-- Courses are pre-loaded — students select from this list when enrolling

INSERT IGNORE INTO course_table (department_code, course_code, course_name) VALUES

-- Accounting
('ACCT', 'ACCT 0104', 'Principles of Accounting I'),
('ACCT', 'ACCT 0105', 'Principles of Accounting II'),
('ACCT', 'ACCT 0205', 'Fund Accounting'),
('ACCT', 'ACCT 0310', 'Federal Income Taxation'),
('ACCT', 'ACCT 0311', 'Auditing'),
('ACCT', 'ACCT 0315', 'Financial Reporting I'),
('ACCT', 'ACCT 0316', 'Financial Reporting II'),
('ACCT', 'ACCT 0317', 'Cost Accounting'),
('ACCT', 'ACCT 0318', 'Financial Reporting III'),
('ACCT', 'ACCT 0322', 'Corporate Taxation: Planning and Practice'),
('ACCT', 'ACCT 0345', 'Accounting Information Systems'),
('ACCT', 'ACCT 0350', 'Special Topics in Accounting'),
('ACCT', 'ACCT 0399', 'Independent Study: Accounting'),

-- Anthropology
('ANTH', 'ANTH 0101', 'Introduction to Anthropology'),
('ANTH', 'ANTH 0200', 'Methods of Ethnography from 1900-Present'),
('ANTH', 'ANTH 0201', 'Cultural Anthropology'),
('ANTH', 'ANTH 0217', 'Culture and Personality'),
('ANTH', 'ANTH 0250', 'Special Topics in Anthropology'),
('ANTH', 'ANTH 0260', 'Introduction to Medical Anthropology'),
('ANTH', 'ANTH 0282', 'Introduction to Archeology'),
('ANTH', 'ANTH 0313', 'Chinese Culture and Society'),
('ANTH', 'ANTH 0320', 'Political Anthropology'),
('ANTH', 'ANTH 0350', 'Special Topics in Anthropology'),

-- Astronomy
('ASTR', 'ASTR 0101', 'Astronomy'),
('ASTR', 'ASTR 0105', 'The Solar System'),
('ASTR', 'ASTR 0121', 'Life in The Universe'),
('ASTR', 'ASTR 0239', 'Special Topics in Astronomy'),
('ASTR', 'ASTR 0349', 'Integrated Physical Science: Astronomy'),
('ASTR', 'ASTR 0350', 'Theoretical or Experimental Research'),
('ASTR', 'ASTR 0398', 'Internship'),
('ASTR', 'ASTR 0399', 'Independent Study'),

-- Biology
('BIOL', 'BIOL 0102', 'Environmental Biology'),
('BIOL', 'BIOL 0104', 'Human Biology'),
('BIOL', 'BIOL 0106', 'Biology Today'),
('BIOL', 'BIOL 0128', 'General Biology II'),
('BIOL', 'BIOL 0129', 'General Biology I'),
('BIOL', 'BIOL 0180', 'Introductory Seminar in Biology'),
('BIOL', 'BIOL 0200', 'Natural History in America'),
('BIOL', 'BIOL 0201', 'General Ecology'),
('BIOL', 'BIOL 0202', 'Conservation Biology'),
('BIOL', 'BIOL 0203', 'Genetics'),
('BIOL', 'BIOL 0204', 'GIS Applications for Natural Sciences'),
('BIOL', 'BIOL 0205', 'Cell Biology'),
('BIOL', 'BIOL 0206', 'Plants and Human Society'),
('BIOL', 'BIOL 0207', 'Developmental Biology'),
('BIOL', 'BIOL 0208', 'Marine Biology'),
('BIOL', 'BIOL 0209', 'Medical Microbiology'),
('BIOL', 'BIOL 0210', 'Histology'),
('BIOL', 'BIOL 0211', 'Plant Biology'),
('BIOL', 'BIOL 0212', 'Mammalogy'),
('BIOL', 'BIOL 0216', 'Flora of Massachusetts'),
('BIOL', 'BIOL 0217', 'Invertebrate Zoology'),
('BIOL', 'BIOL 0218', 'Medical Genetics'),
('BIOL', 'BIOL 0219', 'Aquatic Biology'),
('BIOL', 'BIOL 0221', 'Comparative Physiology'),
('BIOL', 'BIOL 0223', 'Microbiology'),
('BIOL', 'BIOL 0227', 'Comparative Vertebrate Anatomy'),
('BIOL', 'BIOL 0230', 'Evolution'),
('BIOL', 'BIOL 0233', 'Environmental Legislation'),
('BIOL', 'BIOL 0237', 'Human Anatomy and Physiology I'),
('BIOL', 'BIOL 0239', 'Human Anatomy and Physiology II'),
('BIOL', 'BIOL 0240', 'Parasitology'),
('BIOL', 'BIOL 0278', 'Biostatistics'),
('BIOL', 'BIOL 0279', 'Topics in Environmental Studies'),
('BIOL', 'BIOL 0288', 'Writing for Biology'),
('BIOL', 'BIOL 0299', 'Directed Study'),
('BIOL', 'BIOL 0313', 'Immunology'),
('BIOL', 'BIOL 0319', 'Immunology without Lab'),
('BIOL', 'BIOL 0325', 'Ecosystems'),
('BIOL', 'BIOL 0328', 'Biogeography'),
('BIOL', 'BIOL 0333', 'Organismal Neurobiology'),
('BIOL', 'BIOL 0334', 'Animal Behavior'),
('BIOL', 'BIOL 0340', 'Forest Ecology'),
('BIOL', 'BIOL 0342', 'Drugs: From Start to Finish'),
('BIOL', 'BIOL 0377', 'Research Experience'),
('BIOL', 'BIOL 0379', 'Special Topics in Biology'),
('BIOL', 'BIOL 0380', 'Senior Seminar'),
('BIOL', 'BIOL 0388', 'Biology Internship'),
('BIOL', 'BIOL 0390', 'Teaching Secondary School Biology'),
('BIOL', 'BIOL 0399', 'Independent Research'),

-- Computer and Information Science
('CAIS', 'CAIS 0101', 'Computers in Society'),
('CAIS', 'CAIS 0102', 'Computer Science Principles'),
('CAIS', 'CAIS 0105', 'Introduction to Data Science'),
('CAIS', 'CAIS 0117', 'Introduction to Computer Programming'),
('CAIS', 'CAIS 0120', 'Computer Science/Program Design I'),
('CAIS', 'CAIS 0124', 'The Personal Computer'),
('CAIS', 'CAIS 0125', 'Introduction to Computer Information Systems'),
('CAIS', 'CAIS 0132', 'Programming in C++'),
('CAIS', 'CAIS 0200', 'Programming Language Module'),
('CAIS', 'CAIS 0205', 'Introduction to Cobol'),
('CAIS', 'CAIS 0210', 'Database Application Development Techniques'),
('CAIS', 'CAIS 0212', 'Visual Programming Concepts'),
('CAIS', 'CAIS 0216', 'Web-Based Application Development'),
('CAIS', 'CAIS 0218', 'PYTHON II'),
('CAIS', 'CAIS 0220', 'Computer Science/Program Design II'),
('CAIS', 'CAIS 0230', 'Data Structures/Algorithm Analysis'),
('CAIS', 'CAIS 0236', 'Computer Organization and Architecture'),
('CAIS', 'CAIS 0240', 'Software Engineering'),
('CAIS', 'CAIS 0265', 'Introduction to Digital Electronics and Microprocessors'),
('CAIS', 'CAIS 0280', 'Special Topics in Computer and Information Science'),
('CAIS', 'CAIS 0290', 'Introduction to Computer Security'),
('CAIS', 'CAIS 0301', 'Compiler Design'),
('CAIS', 'CAIS 0302', 'Computer Science Seminar'),
('CAIS', 'CAIS 0305', 'Elements of Systems Programming'),
('CAIS', 'CAIS 0307', 'Organization of Programming Languages'),
('CAIS', 'CAIS 0308', 'Advanced Cobol/File Processing'),
('CAIS', 'CAIS 0310', 'Database Management'),
('CAIS', 'CAIS 0311', 'Data Mining'),
('CAIS', 'CAIS 0312', 'End-User Computing: An Overview'),
('CAIS', 'CAIS 0315', 'Multimedia Presentation Technology'),
('CAIS', 'CAIS 0316', 'Web Programming'),
('CAIS', 'CAIS 0337', 'Networking and Client/Server Computing'),
('CAIS', 'CAIS 0339', 'Operating Systems'),
('CAIS', 'CAIS 0341', 'Computer Graphics'),
('CAIS', 'CAIS 0346', 'Systems Analysis and Design'),
('CAIS', 'CAIS 0347', 'Introduction to Networking'),
('CAIS', 'CAIS 0348', 'Computer Simulation'),
('CAIS', 'CAIS 0350', 'Artificial Intelligence'),
('CAIS', 'CAIS 0351', 'Introduction to the Theory of Computation'),
('CAIS', 'CAIS 0353', 'Applied Development Project'),
('CAIS', 'CAIS 0363', 'Computer Science Senior Project'),
('CAIS', 'CAIS 0380', 'Special Topics in Computer and Information Science'),
('CAIS', 'CAIS 0394', 'Data Science Capstone'),
('CAIS', 'CAIS 0396', 'Computer Science Internship A'),
('CAIS', 'CAIS 0397', 'Computer Science Internship B'),

-- Chemistry
('CHEM', 'CHEM 0101', 'Introduction to Chemistry'),
('CHEM', 'CHEM 0103', 'Chemistry of the Life Sciences'),
('CHEM', 'CHEM 0109', 'General Chemistry I'),
('CHEM', 'CHEM 0111', 'General Chemistry II'),
('CHEM', 'CHEM 0201', 'Organic Chemistry I'),
('CHEM', 'CHEM 0203', 'Organic Chemistry II'),
('CHEM', 'CHEM 0211', 'Advanced Inorganic Chemistry'),
('CHEM', 'CHEM 0305', 'Physical Chemistry I'),
('CHEM', 'CHEM 0307', 'Physical Chemistry II'),
('CHEM', 'CHEM 0311', 'Instrumental Analysis'),
('CHEM', 'CHEM 0313', 'Biochemistry I'),
('CHEM', 'CHEM 0315', 'Biochemistry I with Lab'),
('CHEM', 'CHEM 0316', 'Biochemistry II'),
('CHEM', 'CHEM 0350', 'Research Experience'),
('CHEM', 'CHEM 0389', 'Senior Seminar in Chemistry'),
('CHEM', 'CHEM 0398', 'Internship'),
('CHEM', 'CHEM 0399', 'Independent Study'),

-- Communication
('COMM', 'COMM 0101', 'Introduction to Mass Communication'),
('COMM', 'COMM 0102', 'Introduction to Human Communication'),
('COMM', 'COMM 0106', 'Video Production I'),
('COMM', 'COMM 0108', 'Introduction to Film'),
('COMM', 'COMM 0201', 'Introduction to Communication Technology'),
('COMM', 'COMM 0202', 'Introduction to Photography'),
('COMM', 'COMM 0203', 'Principles of Public Relations'),
('COMM', 'COMM 0204', 'Writing for the Media'),
('COMM', 'COMM 0206', 'Video Production II'),
('COMM', 'COMM 0207', 'Communication Ethics'),
('COMM', 'COMM 0209', 'Global Communication'),
('COMM', 'COMM 0210', 'Communication, Culture, and Human Rights'),
('COMM', 'COMM 0211', 'Representation in the Media'),
('COMM', 'COMM 0212', 'Film and Gender'),
('COMM', 'COMM 0213', 'Global Film Studies'),
('COMM', 'COMM 0216', 'Issues in Advertising'),
('COMM', 'COMM 0220', 'Communication and Conflict'),
('COMM', 'COMM 0221', 'Communication Theory'),
('COMM', 'COMM 0222', 'Intercultural Communication'),
('COMM', 'COMM 0223', 'Web Page Design and Construction I'),
('COMM', 'COMM 0230', 'Audio Production I'),
('COMM', 'COMM 0233', 'Documentary Film'),
('COMM', 'COMM 0235', 'The History of Journalism'),
('COMM', 'COMM 0240', 'Communication History'),
('COMM', 'COMM 0245', 'The Silent Film'),
('COMM', 'COMM 0275', 'Journalism I'),
('COMM', 'COMM 0300', 'Food: Communication, Community, and Civic Engagement'),
('COMM', 'COMM 0301', 'International Conflict Resolution'),
('COMM', 'COMM 0303', 'Persuasive Communication'),
('COMM', 'COMM 0305', 'Communication Internship'),
('COMM', 'COMM 0307', 'Communication Law'),
('COMM', 'COMM 0308', 'Multimedia Journalism'),
('COMM', 'COMM 0309', 'Broadcast Journalism'),
('COMM', 'COMM 0310', 'Digital Video Editing'),
('COMM', 'COMM 0312', 'Media Criticism'),
('COMM', 'COMM 0314', 'Senior Thesis/Project'),
('COMM', 'COMM 0316', 'Special Topics in Communication'),
('COMM', 'COMM 0317', 'Health Communication'),
('COMM', 'COMM 0318', 'Social Media, Social Context'),
('COMM', 'COMM 0319', 'Media Literacy'),
('COMM', 'COMM 0320', 'Foundations of Communication Research'),
('COMM', 'COMM 0321', 'Political Communication'),
('COMM', 'COMM 0322', 'Professional Communication'),
('COMM', 'COMM 0323', 'Interpersonal Communication'),
('COMM', 'COMM 0325', 'Photojournalism'),
('COMM', 'COMM 0328', 'Audio Production II'),
('COMM', 'COMM 0329', 'Crime and the Media'),
('COMM', 'COMM 0330', 'Issues in the Media Industries'),
('COMM', 'COMM 0331', 'Web Page Design and Construction II'),
('COMM', 'COMM 0332', 'Writing for the Interactive Media'),
('COMM', 'COMM 0335', 'Media, Technology, and the Future'),
('COMM', 'COMM 0336', 'Advanced Public Relations'),
('COMM', 'COMM 0339', 'Journalism and Society'),
('COMM', 'COMM 0340', 'Organizational Communication'),
('COMM', 'COMM 0342', 'Public Relations Writing'),
('COMM', 'COMM 0375', 'Journalism II'),
('COMM', 'COMM 0394', 'News Editing'),
('COMM', 'COMM 0395', 'Sports Writing'),
('COMM', 'COMM 0399', 'Independent Study'),

-- Criminal Justice
('CRJU', 'CRJU 0101', 'Introduction to Criminal Justice'),
('CRJU', 'CRJU 0121', 'Theories of Crime'),
('CRJU', 'CRJU 0201', 'Law Enforcement and Society'),
('CRJU', 'CRJU 0202', 'Introduction to Corrections'),
('CRJU', 'CRJU 0205', 'American Judicial System'),
('CRJU', 'CRJU 0216', 'Deviance and Culture'),
('CRJU', 'CRJU 0231', 'Research Methods in Criminal Justice'),
('CRJU', 'CRJU 0301', 'Juvenile Procedure'),
('CRJU', 'CRJU 0302', 'Criminal Law'),
('CRJU', 'CRJU 0303', 'Patterns of Criminality'),
('CRJU', 'CRJU 0304', 'Prevention and Control'),
('CRJU', 'CRJU 0305', 'Principles of Evidence and Proof'),
('CRJU', 'CRJU 0306', 'Contemporary Problems in Corrections'),
('CRJU', 'CRJU 0307', 'Contemporary Problems in Law Enforcement'),
('CRJU', 'CRJU 0308', 'Rights of the Convicted'),
('CRJU', 'CRJU 0309', 'Principles of Criminal Investigation'),
('CRJU', 'CRJU 0310', 'Organized and White Collar Crime'),
('CRJU', 'CRJU 0311', 'Victimology'),
('CRJU', 'CRJU 0312', 'Women in the Criminal Justice System'),
('CRJU', 'CRJU 0313', 'Statistics in Criminal Justice'),
('CRJU', 'CRJU 0314', 'Seminar on Offender Rehabilitation'),
('CRJU', 'CRJU 0316', 'Civil Liabilities of Criminal Justice Professionals'),
('CRJU', 'CRJU 0317', 'Evolution of American Law Enforcement'),
('CRJU', 'CRJU 0318', 'The Theory and Practice of Mandated Reporting'),
('CRJU', 'CRJU 0319', 'Economic Crime'),
('CRJU', 'CRJU 0320', 'Criminal Procedure: Fourth Amendment Rights'),
('CRJU', 'CRJU 0322', 'Youth Gangs'),
('CRJU', 'CRJU 0323', 'Religion and Crime in Contemporary America'),
('CRJU', 'CRJU 0324', 'Restorative Community Justice'),
('CRJU', 'CRJU 0325', 'Capital Punishment'),
('CRJU', 'CRJU 0326', 'Planned Change in Criminal Justice'),
('CRJU', 'CRJU 0327', 'Race and Ethnicity in the Criminal Justice System'),
('CRJU', 'CRJU 0328', 'Computer Application in Crime Analysis'),
('CRJU', 'CRJU 0329', 'Crime and the Media'),
('CRJU', 'CRJU 0330', 'Criminal Justice Administration'),
('CRJU', 'CRJU 0332', 'Homicide'),
('CRJU', 'CRJU 0333', 'Terrorism'),
('CRJU', 'CRJU 0334', 'Drugs and Crime'),
('CRJU', 'CRJU 0335', 'Comparative Criminal Justice Systems'),
('CRJU', 'CRJU 0336', 'Supervisory Practices in Law Enforcement'),
('CRJU', 'CRJU 0337', 'Criminal Justice Ethics'),
('CRJU', 'CRJU 0339', 'Probation, Parole, and Community Corrections'),
('CRJU', 'CRJU 0353', 'Corruption and Political Crime'),
('CRJU', 'CRJU 0354', 'Evaluating Criminal Offenders'),
('CRJU', 'CRJU 0355', 'High Profile Crimes and Trials'),
('CRJU', 'CRJU 0357', 'Juveniles and Treatment'),
('CRJU', 'CRJU 0358', 'Sanctioning Sexual Offenders'),
('CRJU', 'CRJU 0359', 'GIS Applications in Crime Analysis'),
('CRJU', 'CRJU 0360', 'Violence and Aggression'),
('CRJU', 'CRJU 0361', 'Researching Theories of Crime'),
('CRJU', 'CRJU 0362', 'Correctional Theory'),
('CRJU', 'CRJU 0365', 'Evidence-Based Crime Policy'),
('CRJU', 'CRJU 0398', 'Field Practicum in Criminal Justice'),
('CRJU', 'CRJU 0399', 'Independent Study'),

-- Economics
('ECON', 'ECON 0101', 'Principles of Macroeconomics'),
('ECON', 'ECON 0102', 'Principles of Microeconomics'),
('ECON', 'ECON 0201', 'Intermediate Microeconomics'),
('ECON', 'ECON 0202', 'Intermediate Macroeconomics'),
('ECON', 'ECON 0204', 'Introduction to Mathematical Economics'),
('ECON', 'ECON 0300', 'Money and Banking'),
('ECON', 'ECON 0301', 'Economics and Law'),
('ECON', 'ECON 0302', 'Economic History of the United States'),
('ECON', 'ECON 0303', 'Economics of Development'),
('ECON', 'ECON 0304', 'Urban Economics'),
('ECON', 'ECON 0305', 'Introduction to Econometric Methods'),
('ECON', 'ECON 0306', 'Managerial Economics'),
('ECON', 'ECON 0307', 'Economics, Gender, Race and Ethnicity'),
('ECON', 'ECON 0308', 'Behavioral Economics'),
('ECON', 'ECON 0309', 'Health Economics'),
('ECON', 'ECON 0312', 'Labor Economics'),
('ECON', 'ECON 0314', 'Industrial Organization'),
('ECON', 'ECON 0315', 'Public Finance'),
('ECON', 'ECON 0316', 'Economic History of Europe'),
('ECON', 'ECON 0318', 'International Economics'),
('ECON', 'ECON 0319', 'Development of Economic Thought'),
('ECON', 'ECON 0320', 'Environmental Economics'),
('ECON', 'ECON 0321', 'Natural Resource Economics'),
('ECON', 'ECON 0322', 'The Economics of Sports'),
('ECON', 'ECON 0350', 'Current Economic Issues'),
('ECON', 'ECON 0351', 'Special Topics in Economics'),
('ECON', 'ECON 0398', 'Senior Research Seminar'),
('ECON', 'ECON 0399', 'Independent Study'),

-- Education
('EDUC', 'EDUC 0201', 'Learning and Assessment'),
('EDUC', 'EDUC 0207', 'Philosophy of Education'),
('EDUC', 'EDUC 0208', 'Teaching in U.S. Secondary Schools'),
('EDUC', 'EDUC 0215', 'Theory of Critical Multicultural Education'),
('EDUC', 'EDUC 0219', 'Social Foundation of Early Childhood Education'),
('EDUC', 'EDUC 0220', 'Schools in US Society'),
('EDUC', 'EDUC 0221', 'Foundations of Special Education'),
('EDUC', 'EDUC 0222', 'Learning Disabilities and Instructional Strategies'),
('EDUC', 'EDUC 0223', 'Critical Roles and Responsibilities of the Special Educator'),
('EDUC', 'EDUC 0260', 'Global Civic Engagement'),
('EDUC', 'EDUC 0300', 'Practicum Seminar'),
('EDUC', 'EDUC 0301', 'Methods of Teaching Mathematics, Elementary 1-6'),
('EDUC', 'EDUC 0303', 'Foundations of Reading'),
('EDUC', 'EDUC 0304', 'Teaching Writing: PreK-6'),
('EDUC', 'EDUC 0305', 'Teaching Writing, Children''s Literature, and Disciplinary Literacy'),
('EDUC', 'EDUC 0306', 'Elementary Curriculum and Instruction'),
('EDUC', 'EDUC 0308', 'Early Childhood Curriculum'),
('EDUC', 'EDUC 0309', 'Children''s Literature'),
('EDUC', 'EDUC 0311', 'Social Studies in the Elementary School'),
('EDUC', 'EDUC 0319', 'Foundations of Teaching and Learning'),
('EDUC', 'EDUC 0320', 'Field Experience 1: Becoming a Teacher'),
('EDUC', 'EDUC 0325', 'Practices of Critical Multicultural Education'),
('EDUC', 'EDUC 0363', 'Sheltered English Immersion'),
('EDUC', 'EDUC 0399', 'Independent Study'),

-- English
('ENGL', 'ENGL 0101', 'Composition I: Rhetoric and Inquiry'),
('ENGL', 'ENGL 0103', 'Speech'),
('ENGL', 'ENGL 0108', 'Introduction to Film'),
('ENGL', 'ENGL 0112', 'Introduction to Black American Literature'),
('ENGL', 'ENGL 0115', 'Introduction to Native American Literature'),
('ENGL', 'ENGL 0204', 'Composition II: Rhetoric and Research'),
('ENGL', 'ENGL 0206', 'Principles and Applications of Grammar'),
('ENGL', 'ENGL 0210', 'British Literature to 1780'),
('ENGL', 'ENGL 0212', 'British Literature from 1780 to the Present'),
('ENGL', 'ENGL 0215', 'Introduction to American Literature'),
('ENGL', 'ENGL 0216', 'American Literature to 1865'),
('ENGL', 'ENGL 0217', 'American Literature Since 1865'),
('ENGL', 'ENGL 0218', 'Postcolonial Literature and Theory'),
('ENGL', 'ENGL 0221', 'World Literature'),
('ENGL', 'ENGL 0228', 'Introduction to Shakespeare'),
('ENGL', 'ENGL 0240', 'Cultural Studies'),
('ENGL', 'ENGL 0246', 'Creative Writing'),
('ENGL', 'ENGL 0275', 'Journalism I'),
('ENGL', 'ENGL 0295', 'Gateway to Advanced Literary Study'),
('ENGL', 'ENGL 0300', 'Development of the Novel'),
('ENGL', 'ENGL 0305', 'Grant Writing'),
('ENGL', 'ENGL 0317', 'Shakespeare: Tragedies and Histories'),
('ENGL', 'ENGL 0318', 'Shakespeare: Comedies and Romances'),
('ENGL', 'ENGL 0323', 'The American Novel'),
('ENGL', 'ENGL 0340', 'Creative Non-Fiction'),
('ENGL', 'ENGL 0345', 'Writing Fiction'),
('ENGL', 'ENGL 0346', 'Writing Poetry'),
('ENGL', 'ENGL 0347', 'Advanced Critical Writing'),
('ENGL', 'ENGL 0350', 'Methods of Teaching English in the Secondary and/or Middle School'),
('ENGL', 'ENGL 0367', 'Film Theory and Criticism'),
('ENGL', 'ENGL 0371', 'Playwriting'),
('ENGL', 'ENGL 0375', 'Journalism II'),
('ENGL', 'ENGL 0377', 'Feature Writing'),
('ENGL', 'ENGL 0380', 'Internship in English'),
('ENGL', 'ENGL 0385', 'Screenwriting for Feature Film'),
('ENGL', 'ENGL 0392', 'Business and Technical Writing'),
('ENGL', 'ENGL 0399', 'Independent Study'),

-- Environmental Science
('ENVS', 'ENVS 0101', 'Principles of Environmental Science'),
('ENVS', 'ENVS 0105', 'Natural History and Field Techniques'),
('ENVS', 'ENVS 0106', 'Introduction to Environmental Analysis'),
('ENVS', 'ENVS 0209', 'Wildlife Biology'),
('ENVS', 'ENVS 0210', 'Environmental Chemistry, Toxicology and Pollution'),
('ENVS', 'ENVS 0215', 'Environmental Education and Communication'),
('ENVS', 'ENVS 0220', 'Surface and Groundwater Hydrology'),
('ENVS', 'ENVS 0225', 'Natural Resource Conservation and Management'),
('ENVS', 'ENVS 0230', 'Estimating Wildlife Populations'),
('ENVS', 'ENVS 0233', 'Environmental Legislation'),
('ENVS', 'ENVS 0236', 'Environmental Analysis II'),
('ENVS', 'ENVS 0238', 'Environmental Impact Analysis'),
('ENVS', 'ENVS 0240', 'Writing for Environmental Science'),
('ENVS', 'ENVS 0241', 'Restoration Ecology'),
('ENVS', 'ENVS 0245', 'Sustainable Energy'),
('ENVS', 'ENVS 0251', 'Water Resources Planning and Management'),
('ENVS', 'ENVS 0255', 'Environmental Soil Science'),
('ENVS', 'ENVS 0300', 'Wetlands Assessment and Planning'),
('ENVS', 'ENVS 0309', 'Wildlife Ecology and Management'),
('ENVS', 'ENVS 0311', 'Environmental Monitoring and Analysis'),
('ENVS', 'ENVS 0330', 'Environmental Data Analysis'),
('ENVS', 'ENVS 0341', 'Ecological Restoration'),
('ENVS', 'ENVS 0350', 'Environmental Science Internship'),
('ENVS', 'ENVS 0390', 'Environmental Science Senior Seminar'),
('ENVS', 'ENVS 0399', 'Independent Research'),

-- Ethnic and Gender Studies
('EGST', 'EGST 0101', 'Introduction to Comparative Ethnic Studies'),
('EGST', 'EGST 0102', 'Introduction to Women''s and Gender Studies'),
('EGST', 'EGST 0201', 'Critical Theories in Ethnic and Gender Studies'),
('EGST', 'EGST 0203', 'Introduction to African American Studies'),
('EGST', 'EGST 0204', 'Introduction to Latino/a Studies'),
('EGST', 'EGST 0205', 'Introduction to Gay And Lesbian Studies'),
('EGST', 'EGST 0208', 'Hip Hop Cultures'),
('EGST', 'EGST 0212', 'Introduction to Asian American Studies'),
('EGST', 'EGST 0218', 'Latina Feminism'),
('EGST', 'EGST 0301', 'Seminar in Postcolonial Studies'),
('EGST', 'EGST 0305', 'Critical Race Studies'),
('EGST', 'EGST 0396', 'Capstone Seminar in Ethnic and Gender Studies'),
('EGST', 'EGST 0398', 'EGST Internship'),

-- Finance
('FINC', 'FINC 0102', 'Personal Financial Planning'),
('FINC', 'FINC 0207', 'Financial Management'),
('FINC', 'FINC 0305', 'Introduction to Econometric Methods'),
('FINC', 'FINC 0306', 'Managerial Economics'),
('FINC', 'FINC 0312', 'Investments: Security Analysis'),
('FINC', 'FINC 0314', 'Industrial Organization'),
('FINC', 'FINC 0318', 'Advanced Financial Management'),
('FINC', 'FINC 0319', 'Investments: Portfolio Management'),
('FINC', 'FINC 0320', 'Money and Banking'),
('FINC', 'FINC 0326', 'Insurance and Risk Management'),
('FINC', 'FINC 0350', 'Special Topics in Finance'),
('FINC', 'FINC 0399', 'Independent Study: Finance'),

-- Geography, Planning and Sustainability
('GPS', 'GPS 0101', 'World Regional Geography'),
('GPS', 'GPS 0102', 'Physical Geography'),
('GPS', 'GPS 0105', 'Introduction to Community Planning'),
('GPS', 'GPS 0106', 'Environment, Sustainability and Society'),
('GPS', 'GPS 0107', 'Climate Change'),
('GPS', 'GPS 0203', 'Geography of Hunger and Poverty in the United States'),
('GPS', 'GPS 0204', 'Housing in America'),
('GPS', 'GPS 0210', 'Cultural Geography'),
('GPS', 'GPS 0217', 'Contemporary Global Issues'),
('GPS', 'GPS 0219', 'Land Use and Resource Planning'),
('GPS', 'GPS 0230', 'Meteorology'),
('GPS', 'GPS 0244', 'Introduction to Geographic Information Systems'),
('GPS', 'GPS 0245', 'Sustainable Energy'),
('GPS', 'GPS 0344', 'Advanced Geographic Information Systems'),
('GPS', 'GPS 0391', 'Seminar in Regional and Environmental Planning'),
('GPS', 'GPS 0399', 'Independent Study'),

-- Geology
('GEOL', 'GEOL 0101', 'Physical Geology with Laboratory'),
('GEOL', 'GEOL 0102', 'Physical Geology'),
('GEOL', 'GEOL 0106', 'Historical Geology'),
('GEOL', 'GEOL 0108', 'General Oceanography'),
('GEOL', 'GEOL 0124', 'Geologic Hazards'),
('GEOL', 'GEOL 0205', 'Environmental Geology'),
('GEOL', 'GEOL 0220', 'Surface and Groundwater Hydrology'),
('GEOL', 'GEOL 0398', 'Internship'),
('GEOL', 'GEOL 0399', 'Independent Study'),

-- General Science
('GNSC', 'GNSC 0101', 'Physical Science'),
('GNSC', 'GNSC 0330', 'Science, Technology and Society'),
('GNSC', 'GNSC 0349', 'Research Methods for the Physical Sciences'),
('GNSC', 'GNSC 0350', 'Research Experience'),
('GNSC', 'GNSC 0360', 'Methods of Science Education for Pre-K-6'),
('GNSC', 'GNSC 0383', 'Senior Seminar in General Science'),
('GNSC', 'GNSC 0399', 'Independent Study'),

-- Gerontology
('GERO', 'GERO 0101', 'Introduction to Gerontology'),
('GERO', 'GERO 0201', 'Health and Physical Aging'),
('GERO', 'GERO 0300', 'Caregiving and Carework'),
('GERO', 'GERO 0370', 'Gerontology Internship'),
('GERO', 'GERO 0399', 'Independent Study in Gerontology'),

-- Health Sciences
('HESC', 'HESC 0101', 'Introduction to the Health Care Practice'),
('HESC', 'HESC 0201', 'Human Assessment'),
('HESC', 'HESC 0250', 'Medical Ethics'),
('HESC', 'HESC 0350', 'Research Methods in Evidence Based Practice'),
('HESC', 'HESC 0380', 'Public Health Intervention'),

-- History
('HIST', 'HIST 0101', 'Western Experience I'),
('HIST', 'HIST 0102', 'Western Experience II'),
('HIST', 'HIST 0113', 'World History to 1600'),
('HIST', 'HIST 0114', 'Modern World History'),
('HIST', 'HIST 0130', 'United States History and Government'),
('HIST', 'HIST 0131', 'United States History and Government to 1865'),
('HIST', 'HIST 0132', 'United States History and Government 1865-Present'),
('HIST', 'HIST 0201', 'Medieval Europe'),
('HIST', 'HIST 0202', 'Introduction to Historical Research and Analysis'),
('HIST', 'HIST 0211', 'Europe Since 1919'),
('HIST', 'HIST 0215', 'Introduction to the Middle East, Africa and Asia'),
('HIST', 'HIST 0243', 'United States History, 1932-Present'),
('HIST', 'HIST 0251', 'American Colonial History, 1400-1763'),
('HIST', 'HIST 0264', 'African American History'),
('HIST', 'HIST 0266', 'History of Baseball'),
('HIST', 'HIST 0267', 'Sports in World History'),
('HIST', 'HIST 0275', 'African-American History and Civil Rights Since 1865'),
('HIST', 'HIST 0276', 'Latin America to 1800'),
('HIST', 'HIST 0277', 'Latin America Since 1800'),
('HIST', 'HIST 0283', 'Modern Africa'),
('HIST', 'HIST 0285', 'Public History: Theory and Practice'),
('HIST', 'HIST 0290', 'Special Topics in Comparative History'),
('HIST', 'HIST 0306', 'U.S. Immigration History'),
('HIST', 'HIST 0311', 'Modern Civil Rights Movements 1945-Present'),
('HIST', 'HIST 0332', 'Methods of Teaching History: Middle and Secondary'),
('HIST', 'HIST 0352', 'The American Revolutionary Era and the Early Republic'),
('HIST', 'HIST 0357', 'The Civil War and Reconstruction, 1845-1877'),
('HIST', 'HIST 0359', 'Cold War Era, 1945-1990'),
('HIST', 'HIST 0362', 'Native American History'),
('HIST', 'HIST 0363', 'U.S. in the 1960s'),
('HIST', 'HIST 0395', 'Senior Seminar'),
('HIST', 'HIST 0399', 'Independent Study'),

-- Honors
('HNRS', 'HNRS 0101', 'Honors Discovery Seminar'),
('HNRS', 'HNRS 0201', 'Introduction to the Senior Honors Project'),
('HNRS', 'HNRS 0301', 'Upper-Level Interdisciplinary Honors Seminar'),
('HNRS', 'HNRS 0390', 'Honors Program Internship'),

-- Languages
('LANG', 'LANG 0210', 'Language Culture and Society'),
('LANG', 'LANG 0300', 'Methods of Teaching Foreign Languages'),

-- Latin American and Caribbean Studies
('LACS', 'LACS 0101', 'Introduction to Latin American and Caribbean Studies'),
('LACS', 'LACS 0301', 'Seminar in Latin American and Caribbean Studies'),
('LACS', 'LACS 0399', 'Independent Study in Latin America and Caribbean Studies'),

-- American Sign Language
('LASL', 'LASL 0101', 'American Sign Language I'),
('LASL', 'LASL 0102', 'American Sign Language II'),

-- Arabic
('LARA', 'LARA 0101', 'Arabic I'),
('LARA', 'LARA 0102', 'Arabic II'),
('LARA', 'LARA 0103', 'Arabic III'),
('LARA', 'LARA 0104', 'Arabic IV'),

-- Chinese
('LCHI', 'LCHI 0101', 'Chinese I'),
('LCHI', 'LCHI 0102', 'Chinese II'),
('LCHI', 'LCHI 0103', 'Chinese III'),
('LCHI', 'LCHI 0104', 'Chinese IV'),

-- Cultural Studies
('LCUL', 'LCUL 0201', 'Women in the Hispanic World'),
('LCUL', 'LCUL 0210', 'U.S. Latino/a Cultural Studies'),
('LCUL', 'LCUL 0220', 'Envisioning the Americas'),

-- French
('LFRE', 'LFRE 0101', 'French I'),
('LFRE', 'LFRE 0102', 'French II'),
('LFRE', 'LFRE 0103', 'French III'),
('LFRE', 'LFRE 0104', 'French IV'),
('LFRE', 'LFRE 0201', 'Reading French Texts'),
('LFRE', 'LFRE 0205', 'Speaking and Writing French: Intermediate Level'),
('LFRE', 'LFRE 0305', 'Speaking and Writing French: Advanced Level'),
('LFRE', 'LFRE 0340', 'Special Topics in French'),
('LFRE', 'LFRE 0399', 'Independent Study'),

-- Literature
('LLIT', 'LLIT 0201', 'Women Writers of the Americas: Global'),
('LLIT', 'LLIT 0202', 'Women Writers of the Americas: US'),
('LLIT', 'LLIT 0210', 'Studies in the Literature of Africa and the African Diaspora'),
('LLIT', 'LLIT 0220', 'Studies in European Cultures'),
('LLIT', 'LLIT 0232', 'Puerto Rican Literatures'),
('LLIT', 'LLIT 0310', 'Seminar in Hispanic Studies'),
('LLIT', 'LLIT 0320', 'U.S. Latino/a Drama'),

-- Spanish
('LSPA', 'LSPA 0101', 'Spanish I'),
('LSPA', 'LSPA 0102', 'Spanish II'),
('LSPA', 'LSPA 0103', 'Spanish III'),
('LSPA', 'LSPA 0104', 'Spanish IV'),
('LSPA', 'LSPA 0120', 'Intensive Spanish I and II'),
('LSPA', 'LSPA 0205', 'Spanish Composition'),
('LSPA', 'LSPA 0212', 'Spanish for Heritage Speakers'),
('LSPA', 'LSPA 0215', 'Speaking and Writing Spanish'),
('LSPA', 'LSPA 0302', 'Topics in Hispanic Cultural Studies'),
('LSPA', 'LSPA 0314', 'Spanish for the Professions'),
('LSPA', 'LSPA 0318', 'Spanish Interpreting I'),
('LSPA', 'LSPA 0328', 'Spanish Interpreting II'),
('LSPA', 'LSPA 0330', 'Methods and Techniques of Translation'),
('LSPA', 'LSPA 0397', 'Capstone'),
('LSPA', 'LSPA 0398', 'Internship: Spanish in the Community'),
('LSPA', 'LSPA 0399', 'Independent Study'),

-- Management
('MGMT', 'MGMT 0101', 'Introduction to Business'),
('MGMT', 'MGMT 0107', 'Software Applications in Management'),
('MGMT', 'MGMT 0220', 'Production/Operations Management'),
('MGMT', 'MGMT 0221', 'Business Management: Organizational Development and Management Principles'),
('MGMT', 'MGMT 0224', 'Business Analytics'),
('MGMT', 'MGMT 0241', 'Business Law I'),
('MGMT', 'MGMT 0250', 'Quantitative Approaches to Business Decisions'),
('MGMT', 'MGMT 0301', 'Labor Relations'),
('MGMT', 'MGMT 0302', 'Small Business Management'),
('MGMT', 'MGMT 0308', 'Organizational Development and Behavior'),
('MGMT', 'MGMT 0314', 'Human Resource Management'),
('MGMT', 'MGMT 0320', 'Applied Senior Project'),
('MGMT', 'MGMT 0321', 'Management Information Systems'),
('MGMT', 'MGMT 0325', 'Business Policy and Strategy'),
('MGMT', 'MGMT 0338', 'International Business'),
('MGMT', 'MGMT 0342', 'Entrepreneurship'),
('MGMT', 'MGMT 0344', 'Project Management'),
('MGMT', 'MGMT 0346', 'Leadership'),
('MGMT', 'MGMT 0398', 'Business Internship'),
('MGMT', 'MGMT 0399', 'Independent Study: Business Management'),

-- Marketing
('MRKT', 'MRKT 0231', 'Marketing Management'),
('MRKT', 'MRKT 0251', 'Introduction to Commercial Recreation and Tourism'),
('MRKT', 'MRKT 0306', 'Logistics Management'),
('MRKT', 'MRKT 0307', 'Marketing Research Techniques'),
('MRKT', 'MRKT 0309', 'Sales and Sales Management'),
('MRKT', 'MRKT 0328', 'Principles of Advertising'),
('MRKT', 'MRKT 0336', 'Fundamentals of Retailing'),
('MRKT', 'MRKT 0337', 'Consumer Behavior'),
('MRKT', 'MRKT 0350', 'Special Topics in Marketing'),
('MRKT', 'MRKT 0399', 'Independent Study: Marketing'),

-- Mathematics
('MATH', 'MATH 0104', 'Pre-Calculus'),
('MATH', 'MATH 0105', 'Calculus I'),
('MATH', 'MATH 0106', 'Calculus II'),
('MATH', 'MATH 0108', 'Elementary Statistics'),
('MATH', 'MATH 0110', 'Mathematical Explorations'),
('MATH', 'MATH 0111', 'Mathematical Applications'),
('MATH', 'MATH 0113', 'Introduction to Data Science'),
('MATH', 'MATH 0115', 'Mathematics for Business and Social Sciences'),
('MATH', 'MATH 0116', 'Introduction to Mathematical Systems'),
('MATH', 'MATH 0201', 'Calculus III'),
('MATH', 'MATH 0218', 'Linear Algebra'),
('MATH', 'MATH 0220', 'Discrete Structures'),
('MATH', 'MATH 0300', 'Discrete Mathematics with Proofs'),
('MATH', 'MATH 0301', 'Abstract Algebra I'),
('MATH', 'MATH 0304', 'Differential Equations'),
('MATH', 'MATH 0306', 'Modern Geometries'),
('MATH', 'MATH 0308', 'Real Analysis'),
('MATH', 'MATH 0309', 'Topology'),
('MATH', 'MATH 0311', 'Number Theory'),
('MATH', 'MATH 0327', 'History of Mathematics'),
('MATH', 'MATH 0333', 'Applied Statistical and Experimental Design'),
('MATH', 'MATH 0334', 'Operations Research and Modeling'),
('MATH', 'MATH 0335', 'Numerical Analysis'),
('MATH', 'MATH 0340', 'Mathematical Statistics I'),
('MATH', 'MATH 0341', 'Mathematical Statistics II'),
('MATH', 'MATH 0344', 'Probability Theory'),
('MATH', 'MATH 0390', 'Senior Seminar in Mathematics'),
('MATH', 'MATH 0394', 'Data Science Capstone'),
('MATH', 'MATH 0398', 'Internship in Mathematics'),
('MATH', 'MATH 0399', 'Independent Study'),

-- Movement and Physical Education
('MOVP', 'MOVP 0100', 'Science of Physical Activity and Health'),
('MOVP', 'MOVP 0101', 'Professional Issues in Exercise Science'),
('MOVP', 'MOVP 0102', 'Introduction to Athletic Training'),
('MOVP', 'MOVP 0103', 'Introduction to Teaching Physical Education'),
('MOVP', 'MOVP 0108', 'Principles of Health and Wellbeing'),
('MOVP', 'MOVP 0190', 'First Aid and Emergency Care'),
('MOVP', 'MOVP 0202', 'Introduction to Motor Learning'),
('MOVP', 'MOVP 0204', 'Kinesiology'),
('MOVP', 'MOVP 0205', 'Physiology of Exercise'),
('MOVP', 'MOVP 0212', 'Concepts of Nutrition'),
('MOVP', 'MOVP 0215', 'Sports and Exercise Psychology'),
('MOVP', 'MOVP 0220', 'Coaching Principles and Practice'),
('MOVP', 'MOVP 0255', 'Functional Anatomy'),
('MOVP', 'MOVP 0305', 'Principles of Strength and Conditioning'),
('MOVP', 'MOVP 0311', 'Adapted Physical Education'),
('MOVP', 'MOVP 0319', 'General Medical Aspects of Physical Activity'),
('MOVP', 'MOVP 0320', 'Fitness Assessment and Exercise Prescription'),
('MOVP', 'MOVP 0325', 'Women and Sport'),
('MOVP', 'MOVP 0332', 'Nutrition and Human Performance'),
('MOVP', 'MOVP 0360', 'Senior Seminar in Sports Medicine'),
('MOVP', 'MOVP 0390', 'Senior Seminar in Exercise Science'),
('MOVP', 'MOVP 0397', 'Exercise Science Capstone Internship'),
('MOVP', 'MOVP 0399', 'Independent Study'),

-- Music
('MUSC', 'MUSC 0101', 'Music Appreciation'),
('MUSC', 'MUSC 0104', 'World Music'),
('MUSC', 'MUSC 0110', 'Basic Music Theory'),
('MUSC', 'MUSC 0111', 'Music Theory I'),
('MUSC', 'MUSC 0112', 'Music Theory II'),
('MUSC', 'MUSC 0160', 'History of Jazz'),
('MUSC', 'MUSC 0189', 'Introduction to Music Therapy'),
('MUSC', 'MUSC 0200', 'Music History I'),
('MUSC', 'MUSC 0201', 'Music History II'),
('MUSC', 'MUSC 0211', 'Music Theory III'),
('MUSC', 'MUSC 0212', 'Music Theory IV'),
('MUSC', 'MUSC 0221', 'Introduction to Music Education'),
('MUSC', 'MUSC 0230', 'Basic Conducting'),
('MUSC', 'MUSC 0235', 'Music Technology'),
('MUSC', 'MUSC 0282', 'Jazz Improvisation I'),
('MUSC', 'MUSC 0300', 'Music in the Middle Ages and Renaissance'),
('MUSC', 'MUSC 0301', 'Music in the Baroque and Classical Eras'),
('MUSC', 'MUSC 0302', 'Music in the Romantic Era'),
('MUSC', 'MUSC 0303', 'Music in the Twentieth Century'),
('MUSC', 'MUSC 0304', 'American Music'),
('MUSC', 'MUSC 0322', 'Elementary Music Methods'),
('MUSC', 'MUSC 0328', 'Practicum: Music K-12'),
('MUSC', 'MUSC 0334', 'Jazz Pedagogy and Literature'),
('MUSC', 'MUSC 0360', 'Jazz Composition and Arranging I'),
('MUSC', 'MUSC 0390', 'Clinical Improvisation II: Group Process'),
('MUSC', 'MUSC 0395', 'Clinical Music Therapy Practicum'),
('MUSC', 'MUSC 0397', 'Clinical Capstone in Music Therapy'),
('MUSC', 'MUSC 0398', 'Music Therapy Internship'),
('MUSC', 'MUSC 0399', 'Independent Study'),

-- Nursing
('NURS', 'NURS 0100', 'Introduction to Professional Nursing'),
('NURS', 'NURS 0201', 'Fundamentals of Professional Nursing Practice'),
('NURS', 'NURS 0301', 'Professional Nursing: Concepts and Issues in Globalized Healthcare'),
('NURS', 'NURS 0302', 'Advanced Health Assessment'),
('NURS', 'NURS 0305', 'Nursing Research'),
('NURS', 'NURS 0311', 'Community Health Nursing'),
('NURS', 'NURS 0312', 'Nursing Care of the Adult and Older Adult I'),
('NURS', 'NURS 0313', 'Nursing Care of the Adult and Older Adult II'),
('NURS', 'NURS 0316', 'Psychiatric Nursing'),
('NURS', 'NURS 0321', 'Nursing Care of Children and Families'),
('NURS', 'NURS 0335', 'Pathophysiology and Pharmacology I'),
('NURS', 'NURS 0336', 'Pathophysiology and Pharmacology II'),
('NURS', 'NURS 0355', 'Nursing Leadership'),
('NURS', 'NURS 0397', 'Nursing Capstone and Clinical Internship'),
('NURS', 'NURS 0399', 'Independent Study'),

-- Philosophy
('PHIL', 'PHIL 0101', 'Introduction to Social and Political Philosophy'),
('PHIL', 'PHIL 0102', 'Introduction to Ethics'),
('PHIL', 'PHIL 0103', 'Symbolic Logic I'),
('PHIL', 'PHIL 0104', 'Great Philosophical Issues'),
('PHIL', 'PHIL 0107', 'Major Religions of the West'),
('PHIL', 'PHIL 0108', 'Major Religions of the East'),
('PHIL', 'PHIL 0109', 'Introduction to Philosophy of Religion'),
('PHIL', 'PHIL 0110', 'Introduction to Philosophy of Science'),
('PHIL', 'PHIL 0201', 'Ancient Philosophy'),
('PHIL', 'PHIL 0211', 'Asian Philosophy'),
('PHIL', 'PHIL 0216', 'Contemporary Philosophy'),
('PHIL', 'PHIL 0217', 'Philosophy and Film'),
('PHIL', 'PHIL 0300', 'Seminar in Philosophy'),
('PHIL', 'PHIL 0304', 'Seminar in Inference and Inquiry'),
('PHIL', 'PHIL 0305', 'Seminar in Value Theory'),
('PHIL', 'PHIL 0399', 'Independent Study'),

-- Physical Science
('PHSC', 'PHSC 0101', 'Introduction to Physics'),
('PHSC', 'PHSC 0103', 'Energy, Environment and Society'),
('PHSC', 'PHSC 0115', 'General Physics I'),
('PHSC', 'PHSC 0117', 'General Physics II'),
('PHSC', 'PHSC 0125', 'Physics I'),
('PHSC', 'PHSC 0127', 'Physics II'),
('PHSC', 'PHSC 0220', 'Survey of Modern Physics'),
('PHSC', 'PHSC 0398', 'Internship'),
('PHSC', 'PHSC 0399', 'Independent Study'),

-- Political Science
('POLS', 'POLS 0101', 'American National Government'),
('POLS', 'POLS 0103', 'State and Local Government'),
('POLS', 'POLS 0105', 'Law, Courts and Politics'),
('POLS', 'POLS 0204', 'Introduction to Public Administration'),
('POLS', 'POLS 0205', 'Metropolitan Politics'),
('POLS', 'POLS 0206', 'Political Analysis'),
('POLS', 'POLS 0208', 'Constitutional Law'),
('POLS', 'POLS 0209', 'International Relations'),
('POLS', 'POLS 0210', 'Comparative European Government'),
('POLS', 'POLS 0212', 'The U.S. Supreme Court'),
('POLS', 'POLS 0215', 'American Political Thought'),
('POLS', 'POLS 0220', 'International Law and Human Rights'),
('POLS', 'POLS 0224', 'Politics of Developing Countries'),
('POLS', 'POLS 0230', 'Asian Politics'),
('POLS', 'POLS 0231', 'Latin American Politics'),
('POLS', 'POLS 0232', 'Middle East Politics'),
('POLS', 'POLS 0301', 'Classical Political Thought'),
('POLS', 'POLS 0302', 'Modern Political Thought'),
('POLS', 'POLS 0305', 'American Foreign Policy'),
('POLS', 'POLS 0307', 'Presidency and Congress: Political Dynamics'),
('POLS', 'POLS 0309', 'Civil Liberties'),
('POLS', 'POLS 0321', 'American Public Policy'),
('POLS', 'POLS 0330', 'Women and Politics'),
('POLS', 'POLS 0337', 'The World at War'),
('POLS', 'POLS 0397', 'Political Science Internship'),
('POLS', 'POLS 0399', 'Independent Study'),

-- Psychology
('PSYC', 'PSYC 0101', 'Introduction to Psychology'),
('PSYC', 'PSYC 0200', 'Industrial and Organizational Psychology'),
('PSYC', 'PSYC 0201', 'Theories of Personality'),
('PSYC', 'PSYC 0202', 'Child Development'),
('PSYC', 'PSYC 0203', 'Adolescent Development'),
('PSYC', 'PSYC 0204', 'Stress, Coping, and Well-Being'),
('PSYC', 'PSYC 0206', 'Educational Psychology'),
('PSYC', 'PSYC 0207', 'Lifespan Development'),
('PSYC', 'PSYC 0210', 'Psychology of Women'),
('PSYC', 'PSYC 0215', 'Adaptation and Animal Behavior'),
('PSYC', 'PSYC 0219', 'Research Methods in Psychology I'),
('PSYC', 'PSYC 0303', 'Abnormal Psychology'),
('PSYC', 'PSYC 0304', 'Social Psychology'),
('PSYC', 'PSYC 0305', 'Forensic Psychology'),
('PSYC', 'PSYC 0308', 'Statistics for Psychologists'),
('PSYC', 'PSYC 0311', 'Health Psychology'),
('PSYC', 'PSYC 0312', 'Behavioral Neuroscience'),
('PSYC', 'PSYC 0315', 'Evolutionary Psychology'),
('PSYC', 'PSYC 0317', 'Applied Behavior Analysis'),
('PSYC', 'PSYC 0319', 'Research Methods in Psychology II'),
('PSYC', 'PSYC 0322', 'Theories of Counseling'),
('PSYC', 'PSYC 0341', 'Cognitive Psychology'),
('PSYC', 'PSYC 0351', 'Emotion'),
('PSYC', 'PSYC 0363', 'Cross Cultural Psychology'),
('PSYC', 'PSYC 0380', 'Capstone Experience: Positive Psychology'),
('PSYC', 'PSYC 0397', 'Psychology Internship'),
('PSYC', 'PSYC 0399', 'Independent Study in Psychology'),

-- Sociology
('SOCI', 'SOCI 0101', 'Principles of Sociology'),
('SOCI', 'SOCI 0200', 'Cultural Anthropology'),
('SOCI', 'SOCI 0201', 'The Family'),
('SOCI', 'SOCI 0202', 'Race and Ethnic Relations'),
('SOCI', 'SOCI 0216', 'Deviance and Culture'),
('SOCI', 'SOCI 0250', 'Research Methods I'),
('SOCI', 'SOCI 0251', 'Research Methods II: Quantitative Methods'),
('SOCI', 'SOCI 0304', 'Social Change'),
('SOCI', 'SOCI 0305', 'Urban Sociology'),
('SOCI', 'SOCI 0307', 'Social Problems'),
('SOCI', 'SOCI 0308', 'Social Inequality'),
('SOCI', 'SOCI 0311', 'Complex Organizations'),
('SOCI', 'SOCI 0314', 'Collective Behavior and Social Movements'),
('SOCI', 'SOCI 0315', 'Sociology of Gender'),
('SOCI', 'SOCI 0317', 'Deviance and Social Control'),
('SOCI', 'SOCI 0318', 'Sociology of Medical Care'),
('SOCI', 'SOCI 0319', 'Sociology of Sexualities'),
('SOCI', 'SOCI 0320', 'Sociology of Education'),
('SOCI', 'SOCI 0321', 'Sociology of Aging'),
('SOCI', 'SOCI 0330', 'Sociology of Law'),
('SOCI', 'SOCI 0335', 'Sociological Theory'),
('SOCI', 'SOCI 0337', 'Death and Dying'),
('SOCI', 'SOCI 0345', 'Sociology of Globalization'),
('SOCI', 'SOCI 0390', 'Capstone in Sociology'),
('SOCI', 'SOCI 0399', 'Independent Study'),

-- Social Work
('SOCW', 'SOCW 0103', 'Introduction to Social Work and Social Welfare'),
('SOCW', 'SOCW 0204', 'Introduction to Research Methods in Social Work'),
('SOCW', 'SOCW 0241', 'Human Behavior and the Social Environment I'),
('SOCW', 'SOCW 0242', 'Human Behavior and the Social Environment II'),
('SOCW', 'SOCW 0243', 'Social Welfare Policy Analysis'),
('SOCW', 'SOCW 0301', 'Advanced Research Methods'),
('SOCW', 'SOCW 0340', 'Introduction to Generalist Practice'),
('SOCW', 'SOCW 0341', 'Generalist Practice with Communities and Organizations'),
('SOCW', 'SOCW 0342', 'Generalist Practice with Individuals'),
('SOCW', 'SOCW 0343', 'Generalist Practice with Families and Groups'),
('SOCW', 'SOCW 0351', 'Social Work Practicum I'),
('SOCW', 'SOCW 0352', 'Social Work Practicum II'),
('SOCW', 'SOCW 0353', 'Senior Capstone I'),
('SOCW', 'SOCW 0354', 'Senior Capstone II'),
('SOCW', 'SOCW 0360', 'Diversity and Social Justice'),
('SOCW', 'SOCW 0399', 'Independent Study'),

-- Theatre Arts
('THEA', 'THEA 0104', 'Introduction to Theatre'),
('THEA', 'THEA 0121', 'Acting Styles: Techniques, Theory and Practice'),
('THEA', 'THEA 0151', 'Introduction to Performance'),
('THEA', 'THEA 0152', 'Scenography'),
('THEA', 'THEA 0156', 'Stagecraft Techniques'),
('THEA', 'THEA 0251', 'Theatre Management'),
('THEA', 'THEA 0252', 'Acting I'),
('THEA', 'THEA 0253', 'Theatre Workshop'),
('THEA', 'THEA 0255', 'Directing I'),
('THEA', 'THEA 0260', 'Script Analysis and Interpretation'),
('THEA', 'THEA 0261', 'Theatre History: Early Stages'),
('THEA', 'THEA 0262', 'Theatre History: Renaissance to Romanticism'),
('THEA', 'THEA 0263', 'Theatre History: The Modern Stage'),
('THEA', 'THEA 0271', 'Theatre for Social Change'),
('THEA', 'THEA 0330', 'Special Topics in Theatre'),
('THEA', 'THEA 0343', 'Sound Design for Theatre'),
('THEA', 'THEA 0350', 'Dramaturgy'),
('THEA', 'THEA 0354', 'Costume Design'),
('THEA', 'THEA 0357', 'Acting II'),
('THEA', 'THEA 0358', 'Production Seminar'),
('THEA', 'THEA 0359', 'Acting for Film and Television'),
('THEA', 'THEA 0360', 'Theatre Production'),
('THEA', 'THEA 0362', 'Research Seminar in Theatre'),
('THEA', 'THEA 0368', 'Directing II'),
('THEA', 'THEA 0380', 'Professional Theatre Seminar'),
('THEA', 'THEA 0389', 'Scene Design'),
('THEA', 'THEA 0390', 'Lighting Design'),
('THEA', 'THEA 0398', 'Internship in Theatre'),
('THEA', 'THEA 0399', 'Independent Study');


-- ── Gamification badges ──────────────────────────────────────────────────────
INSERT IGNORE INTO badge_table (name, description, icon, point_value) VALUES
('First Group Join',    'Joined your first study group',     '👥', 10),
('Group Starter',       'Created your first study group',    '🚀', 15),
('Active Chatter',      'Sent 10 messages in group chats',   '💬', 20),
('Session Scheduler',   'Scheduled your first study session','📅', 25),
('Point Milestone 100', 'Reached 100 total points',          '🏆', 30);

-- Widen notification type column to fit all enum values (SESSION_RESCHEDULED = 19 chars)
ALTER TABLE notification_table MODIFY COLUMN type VARCHAR(30) NOT NULL;
